(function(){
"use strict";
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
let sb=null,currentUser=null,currentProfile=null,currentListings=[],ratingStats={},isAdmin=false;
const cfg=window.APP_CONFIG||{};
function toast(msg){const e=$("#toast");if(!e)return;e.textContent=msg;e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),3200)}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function openModal(html){const r=$("#modalRoot"),c=$("#modalContent");if(!r||!c){toast("واجهة الحساب ما تهيّأتش.");return}c.innerHTML=html;r.classList.add("open");r.setAttribute("aria-hidden","false");document.body.classList.add("modal-open")}
function closeModal(){const r=$("#modalRoot");if(!r)return;r.classList.remove("open");r.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open")}
function updateAccountButton(){const b=$("#accountTop");if(b)b.textContent=currentUser?(currentProfile?.full_name||"حسابي"):"تسجيل الدخول"}
function requireLogin(){if(!currentUser){authForm("login");return false}return true}
async function loadProfile(){currentProfile=null;isAdmin=false;if(!sb||!currentUser)return;try{const p=await sb.from("profiles").select("*").eq("id",currentUser.id).maybeSingle();currentProfile=p.data||null;const a=await sb.from("admins").select("user_id").eq("user_id",currentUser.id).maybeSingle();isAdmin=!!a.data}catch(e){console.warn(e)}}
function authForm(mode="login"){
 const login=mode==="login";
 openModal(`<div class="modal-kicker">${login?"مرحبا بيك 👋":"أهلا بيك في مورد رزق 🤝"}</div><h2>${login?"تسجيل الدخول":"إنشاء حساب مجاني"}</h2><p class="modal-note">${login?"ادخل لحسابك باش تنجم تنشر وتتواصل.":"التسجيل مجاني. اختار نوع حسابك وابدأ معانا."}</p><form id="authForm" class="form-grid">${login?"":`<label>الاسم الكامل<input name="full_name" required maxlength="100"></label>`}<label>البريد الإلكتروني<input name="email" type="email" required autocomplete="email"></label><label>كلمة السر<input name="password" type="password" minlength="6" required></label>${login?"":`<label>رقم الهاتف<input name="phone" inputmode="tel" maxlength="30"></label><label>الولاية<select name="governorate"><option value="">اختر الولاية</option>${["تونس","أريانة","بن عروس","منوبة","نابل","بنزرت","باجة","جندوبة","الكاف","سليانة","سوسة","المنستير","المهدية","صفاقس","القيروان","القصرين","سيدي بوزيد","قابس","مدنين","تطاوين","قبلي","توزر","قفصة"].map(x=>`<option>${x}</option>`).join("")}</select></label><label>نوع الحساب<select name="account_type"><option value="customer">حريف / طالب خدمة</option><option value="provider">مقدّم خدمة</option><option value="seller">بائع / صاحب سلعة</option></select></label>`}<button class="primary-btn" type="submit">${login?"دخول":"إنشاء الحساب"}</button></form><button class="switch-auth" id="switchAuth" type="button">${login?"ما عندكش حساب؟ أنشئ حساب مجاني":"عندك حساب؟ سجّل الدخول"}</button>`);
 $("#switchAuth").onclick=()=>authForm(login?"signup":"login");
 $("#authForm").onsubmit=async e=>{e.preventDefault();if(!sb){toast("Supabase غير مهيّأ.");return}const fd=new FormData(e.target),email=String(fd.get("email")||"").trim(),password=String(fd.get("password")||""),btn=e.target.querySelector("button[type=submit]");btn.disabled=true;btn.textContent="جاري المعالجة...";try{if(login){const r=await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error;closeModal();toast("تم تسجيل الدخول بنجاح ❤️")}else{const metadata={full_name:String(fd.get("full_name")||"").trim(),phone:String(fd.get("phone")||"").trim()||null,governorate:String(fd.get("governorate")||"").trim()||null,account_type:String(fd.get("account_type")||"customer")};const r=await sb.auth.signUp({email,password,options:{data:metadata}});if(r.error)throw r.error;if(r.data.session){currentUser=r.data.session.user;await loadProfile();updateAccountButton();closeModal();toast("الحساب تخلق بنجاح ❤️")}else openModal(`<div class="success-icon">✉️</div><h2>الحساب تخلق بنجاح</h2><p class="modal-note">ثبت إيميلك من الرسالة إذا كان تأكيد البريد مفعّل، وبعدها سجّل الدخول.</p><button class="primary-btn" id="backLogin">رجوع لتسجيل الدخول</button>`),$("#backLogin").onclick=()=>authForm("login")}}catch(err){toast(err?.message||"صار خطأ.");btn.disabled=false;btn.textContent=login?"دخول":"إنشاء الحساب"}};
}
async function handleAccount(){
 if(!currentUser){authForm("login");return}
 let count=0;if(sb){const r=await sb.from("listings").select("id",{count:"exact",head:true}).eq("owner_id",currentUser.id);count=Number(r.count||0)}
 openModal(`<div class="modal-kicker">حسابك في مورد رزق</div><h2>${esc(currentProfile?.full_name||"مستخدم")}</h2><p class="modal-note">${esc(currentUser.email||"")}</p><div class="account-box"><b>${currentProfile?.account_type==="provider"?"مقدّم خدمة":currentProfile?.account_type==="seller"?"بائع / صاحب سلعة":"حريف / طالب خدمة"}</b><span>${esc(currentProfile?.governorate||"الموقع غير محدد")}</span>${currentProfile?.phone?`<span>📱 ${esc(currentProfile.phone)}</span>`:""}</div><button class="primary-btn" id="myListingsBtn">📋 إعلاناتي (${count})</button>${isAdmin?`<button class="primary-btn" id="adminBtn">🛡️ لوحة الإدارة</button>`:""}<button class="secondary-btn" id="myPublish">➕ نشر إعلان</button><button class="secondary-btn" id="logoutBtn">تسجيل الخروج</button>`);
 $("#myListingsBtn").onclick=myListings;$("#myPublish").onclick=publishForm;$("#adminBtn")?.addEventListener("click",()=>adminPanel("listings"));$("#logoutBtn").onclick=async()=>{await sb.auth.signOut();closeModal();toast("خرجت من الحساب.")};
}
window.handleAccount=handleAccount;
async function loadRatingStats(items){ratingStats={};if(!items.length)return;const r=await sb.from("ratings").select("listing_id,rating").in("listing_id",items.map(x=>x.id)).eq("status","approved");(r.data||[]).forEach(x=>{const s=ratingStats[x.listing_id]||(ratingStats[x.listing_id]={sum:0,count:0});s.sum+=Number(x.rating||0);s.count++;s.avg=s.sum/s.count})}
function renderListings(items){const g=$("#listingGrid");if(!g)return;if(!items.length){g.innerHTML=`<div class="empty-state"><div>📭</div><h3>ما فماش إعلانات مطابقة</h3><p>جرّب كلمة بحث أخرى.</p></div>`;return}g.innerHTML=items.map(x=>{const s=ratingStats[x.id],rating=s?`⭐ ${s.avg.toFixed(1)} (${s.count})`:"⭐ ما فماش تقييمات";const price=x.price!=null?`${Number(x.price).toLocaleString("fr-TN")} د.ت`:(x.price_label||"السعر حسب الطلب");return `<article class="listing"><div class="listing-top"><div class="avatar purple">${esc((x.title||"م").trim().charAt(0))}</div>${x.is_featured?'<span class="verified">★ مميّز</span>':''}</div><span class="tag">${x.listing_type==="product"?"منتج":"خدمة"}</span><h3>${esc(x.title)}</h3><p>${esc(x.description||"").slice(0,150)}</p><div class="listing-meta"><span>📍 ${esc(x.governorate||"تونس")}</span><span>💰 ${esc(price)}</span></div><div class="rating-summary">${rating}</div><div class="listing-actions"><button type="button" class="talk-btn" data-owner="${esc(x.owner_id)}" data-listing="${esc(x.id)}">💬 تواصل</button><button type="button" class="rate-btn" data-owner="${esc(x.owner_id)}" data-listing="${esc(x.id)}">⭐ قيّم</button><button type="button" class="report-btn" data-owner="${esc(x.owner_id)}" data-listing="${esc(x.id)}">🚩 إبلاغ</button></div></article>`}).join("");$$('.talk-btn').forEach(b=>b.onclick=()=>startConversation(b.dataset.listing,b.dataset.owner));$$('.rate-btn').forEach(b=>b.onclick=()=>openRatingForm(b.dataset.listing,b.dataset.owner));$$('.report-btn').forEach(b=>b.onclick=()=>openReportForm(b.dataset.listing,b.dataset.owner))}
async function loadListings(){if(!sb)return;const r=await sb.from("listings").select("id,owner_id,listing_type,title,description,category,subcategory,price,price_label,governorate,delegation,is_featured,created_at").eq("status","approved").order("is_featured",{ascending:false}).order("created_at",{ascending:false}).limit(50);if(r.error){console.warn(r.error);toast("تعذر تحميل الإعلانات حاليا.");return}currentListings=r.data||[];await loadRatingStats(currentListings);renderListings(currentListings)}
function search(term){if(term&&$("#searchInput"))$("#searchInput").value=term;const q=($("#searchInput")?.value||"").trim().toLowerCase(),loc=$("#locationSelect")?.value||"";const items=currentListings.filter(x=>{const t=[x.title,x.description,x.category,x.subcategory,x.governorate,x.delegation].join(" ").toLowerCase();return(!q||t.includes(q))&&(!loc||x.governorate===loc)});renderListings(items);if(!q&&!loc)toast("اكتب شنوّة تلوج ولا اختار المنطقة.");else $("#listings")?.scrollIntoView({behavior:"smooth"})}
async function myListings(){if(!requireLogin())return;const r=await sb.from("listings").select("id,listing_type,title,description,category,price,price_label,governorate,delegation,phone,status,created_at").eq("owner_id",currentUser.id).order("created_at",{ascending:false});if(r.error){toast(r.error.message);return}const items=r.data||[];openModal(`<div class="modal-kicker">لوحة إعلاناتك 📋</div><h2>إعلاناتي</h2><p class="modal-note">تنجم تعدّل ولا تحذف أي إعلان نشرتو.</p><button class="primary-btn" id="newAd">➕ نشر إعلان جديد</button><div class="my-listings-list">${items.length?items.map(x=>`<div class="my-listing-item"><div class="my-listing-head"><span class="tag">${x.listing_type==="product"?"منتج":"خدمة"}</span><span class="my-status">${x.status==="approved"?"منشور":x.status==="pending"?"قيد المراجعة":x.status==="rejected"?"مرفوض":"متوقف"}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.description||"").slice(0,130)}</p><div class="listing-meta"><span>📍 ${esc(x.governorate||"غير محدد")}</span><span>💰 ${esc(x.price!=null?Number(x.price).toLocaleString("fr-TN")+" د.ت":x.price_label||"حسب الطلب")}</span></div><div class="my-listing-actions"><button type="button" class="secondary-btn edit-ad" data-id="${esc(x.id)}">✏️ تعديل</button><button type="button" class="danger-btn delete-ad" data-id="${esc(x.id)}">🗑️ حذف</button></div></div>`).join(""): '<div class="empty-state"><div>📭</div><h3>ما عندك حتى إعلان</h3><p>انشر أول إعلان متاعك.</p></div>'}</div>`);$("#newAd").onclick=publishForm;$$('.edit-ad').forEach(b=>b.onclick=()=>editListing(b.dataset.id));$$('.delete-ad').forEach(b=>b.onclick=()=>deleteListing(b.dataset.id))}
function publishForm(){if(!requireLogin())return;openModal(`<div class="modal-kicker">إعلان جديد 📣</div><h2>انشر خدمتك ولا سلعتك</h2><form id="publishForm" class="form-grid"><label>نوع الإعلان<select name="listing_type"><option value="service">خدمة</option><option value="product">منتج</option></select></label><label>العنوان<input name="title" required maxlength="120"></label><label>الوصف<textarea name="description" required maxlength="1000"></textarea></label><label>التصنيف<input name="category"></label><label>السعر<input name="price" type="number" min="0" step="0.001"></label><label>الولاية<select name="governorate"><option value="">اختر الولاية</option>${["تونس","سوسة","صفاقس","المنستير","نابل","بنزرت","قابس","مدنين"].map(x=>`<option>${x}</option>`).join("")}</select></label><label>المعتمدية<input name="delegation"></label><label>رقم الهاتف<input name="phone" inputmode="tel"></label><button class="primary-btn" type="submit">نشر الإعلان</button></form>`);$("#publishForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),btn=e.target.querySelector("button[type=submit]"),p={owner_id:currentUser.id,listing_type:f.get("listing_type"),title:String(f.get("title")||"").trim(),description:String(f.get("description")||"").trim(),category:f.get("category")||null,price:f.get("price")?Number(f.get("price")):null,governorate:f.get("governorate")||null,delegation:f.get("delegation")||null,phone:f.get("phone")||currentProfile?.phone||null,status:"approved"};btn.disabled=true;btn.textContent="جاري النشر...";const r=await sb.from("listings").insert(p);if(r.error){toast(r.error.message);btn.disabled=false;btn.textContent="نشر الإعلان";return}closeModal();toast("تم نشر إعلانك بنجاح ❤️");loadListings()}}
async function editListing(id){const r=await sb.from("listings").select("*").eq("id",id).eq("owner_id",currentUser.id).single();if(r.error||!r.data){toast("ما عندكش صلاحية تعدل الإعلان.");return}const x=r.data;openModal(`<div class="modal-kicker">تعديل الإعلان ✏️</div><h2>عدّل إعلانك</h2><form id="editForm" class="form-grid"><label>نوع الإعلان<select name="listing_type"><option value="service" ${x.listing_type==="service"?"selected":""}>خدمة</option><option value="product" ${x.listing_type==="product"?"selected":""}>منتج</option></select></label><label>العنوان<input name="title" required value="${esc(x.title)}"></label><label>الوصف<textarea name="description" required>${esc(x.description)}</textarea></label><label>التصنيف<input name="category" value="${esc(x.category||"")}"></label><label>السعر<input name="price" type="number" step="0.001" value="${x.price??""}"></label><label>الولاية<input name="governorate" value="${esc(x.governorate||"")}"></label><label>المعتمدية<input name="delegation" value="${esc(x.delegation||"")}"></label><label>الهاتف<input name="phone" value="${esc(x.phone||"")}"></label><button class="primary-btn" type="submit">حفظ التعديلات</button></form>`);$("#editForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),btn=e.target.querySelector("button[type=submit"]);btn.disabled=true;const p={listing_type:f.get("listing_type"),title:f.get("title"),description:f.get("description"),category:f.get("category")||null,price:f.get("price")?Number(f.get("price")):null,governorate:f.get("governorate")||null,delegation:f.get("delegation")||null,phone:f.get("phone")||null};const z=await sb.from("listings").update(p).eq("id",id).eq("owner_id",currentUser.id);if(z.error){toast(z.error.message);btn.disabled=false;return}toast("تم تعديل الإعلان بنجاح ❤️");await loadListings();myListings()}}
async function deleteListing(id){if(!confirm("متأكد تحب تحذف الإعلان نهائيا؟"))return;const r=await sb.from("listings").delete().eq("id",id).eq("owner_id",currentUser.id);if(r.error){toast(r.error.message);return}toast("تم حذف الإعلان 🗑️");await loadListings();myListings()}
async function openRatingForm(listingId,ownerId){if(!requireLogin())return;if(currentUser.id===ownerId){toast("ما تنجمش تقيّم إعلانك.");return}const old=await sb.from("ratings").select("id").eq("listing_id",listingId).eq("reviewer_id",currentUser.id).maybeSingle();if(old.data){toast("سبق وقيّمت الإعلان هذا.");return}openModal(`<div class="modal-kicker">تقييم ⭐</div><h2>قيّم الإعلان</h2><div class="star-picker">${[1,2,3,4,5].map(n=>`<button type="button" class="star-choice" data-rating="${n}">★</button>`).join("")}</div><button type="button" class="primary-btn" id="submitRating" disabled>إرسال التقييم</button>`);let selected=0;$$('.star-choice').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.rating);$$('.star-choice').forEach(s=>s.classList.toggle('selected',Number(s.dataset.rating)<=selected));$("#submitRating").disabled=false});$("#submitRating").onclick=async()=>{const r=await sb.from("ratings").insert({listing_id:listingId,reviewer_id:currentUser.id,rating:selected,status:"approved"});if(r.error){toast(r.error.message);return}closeModal();toast("يعطيك الصحة على التقييم ⭐");loadListings()}}
async function openReportForm(listingId,ownerId){if(!requireLogin())return;if(currentUser.id===ownerId){toast("ما تنجمش تبلغ على إعلانك.");return}openModal(`<div class="modal-kicker">إبلاغ 🚩</div><h2>إبلاغ عن إعلان</h2><form id="reportForm" class="form-grid"><label>السبب<select name="reason" required><option value="">اختار السبب</option><option value="fraud">احتيال أو محاولة نصب</option><option value="misleading">معلومات مضللة</option><option value="inappropriate">محتوى غير مناسب</option><option value="prohibited">سلعة أو خدمة ممنوعة</option><option value="spam">إعلان مزعج / مكرر</option><option value="other">سبب آخر</option></select></label><label>تفاصيل<textarea name="details" maxlength="1000"></textarea></label><button class="primary-btn" type="submit">إرسال البلاغ</button></form>`);$("#reportForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),r=await sb.from("reports").insert({reporter_id:currentUser.id,listing_id:listingId,reported_user_id:ownerId,reason:f.get("reason"),details:String(f.get("details")||"").trim(),status:"pending"});if(r.error){toast(r.error.message);return}closeModal();toast("تم إرسال البلاغ للإدارة 🚩")}}
async function startConversation(listingId,ownerId){if(!requireLogin())return;if(currentUser.id===ownerId){toast("هذا إعلانك إنت.");return}let r=await sb.from("conversations").select("id").eq("listing_id",listingId).eq("customer_id",currentUser.id).eq("owner_id",ownerId).maybeSingle();if(r.data){return openMessageBox(r.data.id)}r=await sb.from("conversations").insert({listing_id:listingId,customer_id:currentUser.id,owner_id:ownerId}).select("id").single();if(r.error){toast(r.error.message);return}openMessageBox(r.data.id)}
async function openMessageBox(id){openModal(`<div class="modal-kicker">رسالة 💬</div><h2>المحادثة</h2><div id="messageHistory" class="message-history">جاري التحميل...</div><form id="messageForm" class="message-form"><input name="message" required maxlength="1000" placeholder="اكتب رسالتك..."><button class="primary-btn" type="submit">إرسال</button></form>`);async function load(){const r=await sb.from("messages").select("id,sender_id,message,created_at").eq("conversation_id",id).order("created_at",{ascending:true});$("#messageHistory").innerHTML=(r.data||[]).map(m=>`<div class="bubble ${m.sender_id===currentUser.id?"mine":"theirs"}">${esc(m.message)}</div>`).join("")||"ابدأ المحادثة 👋"}await load();$("#messageForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),r=await sb.from("messages").insert({conversation_id:id,sender_id:currentUser.id,message:f.get("message")});if(r.error){toast(r.error.message);return}e.target.reset();load()}}
async function notifications(){if(!requireLogin())return;const r=await sb.from("notifications").select("id,title,body,is_read,created_at").eq("user_id",currentUser.id).order("created_at",{ascending:false}).limit(30);if(r.error){toast(r.error.message);return}openModal(`<div class="modal-kicker">الإشعارات 🔔</div><h2>إشعاراتك</h2><div class="notification-list">${(r.data||[]).map(n=>`<div class="notification-item ${n.is_read?"read":"unread"}"><div class="notification-content"><b>${esc(n.title||"إشعار")}</b><p>${esc(n.body||"")}</p></div></div>`).join("")||"ما فماش إشعارات."}</div>`);await sb.from("notifications").update({is_read:true}).eq("user_id",currentUser.id).eq("is_read",false);loadNotificationBadge()}
async function loadNotificationBadge(){if(!sb||!currentUser)return;const r=await sb.from("notifications").select("id",{count:"exact",head:true}).eq("user_id",currentUser.id).eq("is_read",false);const b=$("#notificationBadge");if(b){const n=Number(r.count||0);b.textContent=n>99?"99+":n;b.hidden=n===0}}
async function adminPanel(){if(!isAdmin){toast("ما عندكش صلاحية الإدارة.");return}openModal(`<div class="modal-kicker">🛡️ الإدارة</div><h2>لوحة الإدارة</h2><div id="adminBody">جاري التحميل...</div>`);$(".modal-card")?.classList.add("wide");adminListings()}
async function adminListings(){const b=$("#adminBody");const r=await sb.from("listings").select("id,title,description,status,is_featured,is_top,created_at").order("created_at",{ascending:false}).limit(100);if(r.error){b.textContent=r.error.message;return}b.innerHTML=`<div class="admin-filter"><button data-f="all">الكل</button><button data-f="approved">منشور</button><button data-f="pending">مراجعة</button><button data-f="rejected">مرفوض</button></div><div class="my-listings-list">${(r.data||[]).map(x=>`<div class="my-listing-item" data-id="${esc(x.id)}"><h3>${esc(x.title)}</h3><p>${esc(x.description||"").slice(0,150)}</p><span class="my-status">${esc(x.status)}</span><div class="admin-actions"><button class="secondary-btn" data-status="approved">✅ قبول</button><button class="secondary-btn" data-status="rejected">⛔ رفض</button><button class="secondary-btn" data-status="paused">⏸️ إيقاف</button><button class="danger-btn" data-delete="1">🗑️ حذف</button></div></div>`).join("")||"لا توجد إعلانات"}</div>`;b.querySelectorAll("[data-status]").forEach(btn=>btn.onclick=async()=>{const id=btn.closest("[data-id]").dataset.id,r=await sb.from("listings").update({status:btn.dataset.status}).eq("id",id);if(r.error)toast(r.error.message);else{toast("تمّ ✅");adminListings();loadListings()}});b.querySelectorAll("[data-delete]").forEach(btn=>btn.onclick=async()=>{if(!confirm("تحب تحذف الإعلان؟"))return;const r=await sb.from("listings").delete().eq("id",btn.closest("[data-id]").dataset.id);if(r.error)toast(r.error.message);else{toast("تم الحذف");adminListings();loadListings()}})}
function bind(){
 $("#accountTop")?.addEventListener("click",e=>{e.preventDefault();handleAccount()});$("#accountBtn")?.addEventListener("click",e=>{e.preventDefault();handleAccount()});$("#myListingsNav")?.addEventListener("click",e=>{e.preventDefault();myListings()});$("#publishBtn")?.addEventListener("click",publishForm);$("#messagesBtn")?.addEventListener("click",()=>requireLogin()&&toast("استعمل زر تواصل من إعلان لفتح محادثة."));$("#notificationsBtn")?.addEventListener("click",notifications);$("#searchBtn")?.addEventListener("click",()=>search());$("#searchInput")?.addEventListener("keydown",e=>{if(e.key==="Enter")search()});$$('[data-search]').forEach(b=>b.addEventListener('click',()=>search(b.dataset.search)));$("#searchTop")?.addEventListener("click",()=>{$("#searchInput")?.focus();window.scrollTo({top:0,behavior:"smooth"})});$("#filterBtn")?.addEventListener("click",()=>toast("اكتب كلمة بحث أو اختار الولاية."));$("#menuBtn")?.addEventListener("click",()=>$("#navLinks")?.classList.toggle("open"));$$('[data-close-modal]').forEach(e=>e.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()})
}
async function boot(){try{if(window.supabase&&cfg.supabaseUrl&&cfg.supabasePublishableKey)sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);else{toast("إعداد Supabase ناقص.");return}bind();const s=await sb.auth.getSession();currentUser=s.data.session?.user||null;await loadProfile();updateAccountButton();await loadListings();await loadNotificationBadge();sb.auth.onAuthStateChange(async(_e,session)=>{currentUser=session?.user||null;await loadProfile();updateAccountButton();if(currentUser){loadListings();loadNotificationBadge()}})}catch(e){console.error(e);toast("خطأ في تشغيل التطبيق: "+(e.message||e))}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
